api:
  urlPrefix: /api/v1
springdoc:
  api-docs:
    enabled: true
    path: /api-docs

spring:
  mvc:
    static-path-pattern: /**
  cache:
    type: caffeine

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] traceId: %X{traceId} %logger{32} : %msg%n"
  level:
    root: info
